encoding: UTF-8
permalink: :title

sass:
  sass_dir: _sass

defaults:
- scope:
    path: ""
  values:
    layout: default

future: true

collections:
  audios:
    output: true
  vita_datas:
    output: true