backend:
  name: github
  repo: robin-la-baume/robin-website # Path to your GitHub repository
  branch: main

locale: 'en'

media_folder: "/images/uploads"
public_folder: "/images/uploads"

collections:
  # --------------- Allgemein --------------------
  - label: "Allgemein"
    name: "allgemein"
    files:
    - label: "Allgemein"
      name: "allgemein"
      file: "_data/general.yml"
      fields:
      - label: "Jahr"
        name: "year"
        widget: "string"
        hint: "current year"
      - label: "Vorname"
        name: "forename"
        widget: "string"
      - label: "Zweitname"
        name: "middlename"
        widget: "string"
      - label: "Nachname"
        name: "surename"
        widget: "string"
      - label: "Agentur"
        name: "agency"
        widget: "string"
      - label: "Agenturinhaber:in"
        name: "agency_owner"
        widget: "string"
      - label: "Agentur Straße"
        name: "agency_street"
        widget: "string"
      - label: "Agentur PLZ"
        name: "agency_post_code"
        widget: "string"
      - label: "Agentur Stadt"
        name: "agency_city"
        widget: "string"
      - label: "Agentur Tel.-Nr"
        name: "agency_tel"
        widget: "string"
      - label: "Agentur eMail"
        name: "agency_email"
        widget: "string"

  # --------------- Homepage --------------------
  - label: "Homepage"
    name: "homepage"
    files:
    - label: "Social Media"
      name: "social media"
      file: "_data/social_media.yml"
      fields:
      - label: "Instagram URL"
        name: "instagram_url"
        widget: "string"
      - label: "Theapolis URL"
        name: "theapolis_url"
        widget: "string"
    - label: "News"
      name: "news"
      file: "_data/news.yml"
      fields:
      - label: "News Title"
        name: "news_title"
        widget: "string"
      - label: "News Untertitel #1"
        name: "news_subline_1"
        widget: "string"
      - label: "News Untertitel #2"
        name: "news_subline_2"
        widget: "string"
      - label: "News Datum"
        name: "news_date"
        widget: "datetime"
        default: ""
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
        format: "DD.MM.YYYY"
        picker_utc: true
      - label: "Weitere Infos"
        name: "news_url"
        widget: "string"

  # --------------- Vita --------------------
  - label: "Vita"
    name: "vita"
    folder: "_vita"
    create: true
    slug: "{{year}}-{{month}}-{{hour}}{{minute}}{{second}}_{{head}}"
    fields:
    - label: "Label"
      name: "head"
      widget: "string"
    - label: "Details"
      name: "data"
      widget: "markdown"


# --------------- Audio --------------------
  - label: "Audio"
    name: "audio"
    folder: "_audios"
    create: true
    slug: "{{path_name}}"
    fields:
    - label: "Titel"
      name: "title"
      widget: "string"
    - label: "Pfad"
      name: "pathname"
      widget: "string"
    - label: "Pfad-URL"
      name: "file_path"
      widget: "string"


# --------------- Fotos --------------------
  - label: "Foto"
    name: "foto"
    folder: "_photos"
    create: true
    slug: "{{file_path}}"
    fields:
    - label: "Image"
      name: "file_path"
      widget: "image"
    - label: "Name Fotograf"
      name: "foto_by"
      widget: "string"