backend:
  name: git-gateway
  repo: robin-la-baume/robin-website # Path to your GitHub repository
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "home_page"
    label: "Home Page"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - label: "Instagram URL"
            name: "instagram_url"
            widget: "string"